[package]
name = "day11"
version = "0.1.0"
edition = "2021"
description = "AOC 2022 Day 11"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive-getters = "0.3.0"
itertools = "0.11.0"
log = "0.4.20"
nom = "7.1.3"
